### ISSUE TITLE
Remove pings to the database for each query

### ISSUE THREAD

**Issue by gabriel-vasile** [rakutentech/go-echo-kit#21]
The usual way I've seen this library used:
```go
       db.New().SlaveConn().
		Where("id = ?", 1).
                Find(&res)
```
https://github.com/rakutentech/go-echo-kit/blob/a20e5b30b3a7766b4bf9049d748aecf6218241f8/db/db.go#L211-L222

Having each query also make a ping is wasteful.
These pings bring awful slowdowns because they are network round-trips.

It depends, but it's usually safe to assume the network will be the slowest layer (network > disk > memory) and there really is no  reason in pinging the database so often.

**Comment by kevincobain2000** [comment]
Yes that is a good find.
This entire lib is marked for abolishment tho. There are other issues as well, such as instead of this lib reading `env`, should pass params, and not `panic` inside this lib but just return `err` etc etc.
Feel free to fix it and submit a pull req. I ll make you admin on this repo upon that.
